### ISSUE TITLE
rake breaks on 'brew install brew-cask'

### ISSUE THREAD

**Issue by willfaught** [square/maximum-awesome#225]
# Output

```
$ rake

-- Homebrew --------------------------------------------------------------------

-- Homebrew Cask ---------------------------------------------------------------
brew install brew-cask 
Error: No available formula with the name "brew-cask" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
This formula was found in a tap:
homebrew/completions/brew-cask-completion
To install it, run:
  brew install homebrew/completions/brew-cask-completion
rake aborted!
Command failed with status (1): [brew install brew-cask ...]
/Users/Will/.maximum-awesome/Rakefile:9:in `brew_install'
/Users/Will/.maximum-awesome/Rakefile:137:in `block (2 levels) in <top (required)>'
/Users/Will/.maximum-awesome/Rakefile:232:in `block in <top (required)>'
Tasks: TOP => install:brew_cask
(See full trace by running task with --trace)
```
# Full trace

```
$ rake --trace
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:684:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
```

**Comment by julieushpa** [comment]
I noticed that the maximum-awesome rake runs 'brew install brew-cask' but caskroom says it's not longer necessary to run that: https://github.com/caskroom/homebrew-cask/releases (as of Dec 2015).

**Comment by julieushpa** [comment]
also note that someone is working on a fix: https://github.com/square/maximum-awesome/pull/224

i manually ran ```brew tap caskroom/task``` and then edited my Rakefile and i'm up and running! i commented out line 234: ```Rake::Task['install:brew_cask'].invoke``` (also line 137, but it shouldn't be executed)

i do seem to have some errors, but it could be because of previously installed vim customization.
